packages:
  - "packages/*"
  - "apps/*"

# Exclude test fixtures and build outputs
exclude:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/__tests__/fixtures/**"
  - "**/coverage/**"